First review
alekseevgeorgy/yard-frontend pull request #2
Opened 2017-06-13 16:09 UTC by alekseevgeorgy

2017-06-13 17:34 UTC, imevro requested changes
Битые картинки и у навбара нет бэкграунда https://rawgit.com/alekseevgeorgy/yard-frontend/develop/complexes.html

https://validator.w3.org/nu/?doc=https%3A%2F%2Frawgit.com%2Falekseevgeorgy%2Fyard-frontend%2Fdevelop%2Fcomplexes.html

2017-06-13 17:35 UTC, evgenyrodionov commented
Название пуллреквеста смени, что за фёст ревью

2017-06-13 21:23 UTC, imevro requested changes
Отступы в футере не как в макете
что с линией внизу https://www.dropbox.com/s/x2fogi0ydk5hd4a/Screenshot%202017-06-14%2000.23.01.png?dl=0

2017-06-14 13:40 UTC, imevro requested changes
Фикси замечания, а также что случилось с картинками https://rawgit.com/alekseevgeorgy/yard-frontend/develop/complexes.html

2017-06-14 13:40 UTC, evgenyrodionov commented on complexes.html
> +    <header class="header row">
Не смешивай сетку и свои классы

2017-06-14 13:40 UTC, evgenyrodionov commented on complexes.html
> +      <button name="contact_button">Contact The Team</button>
Тут андер_скор

2017-06-14 13:40 UTC, evgenyrodionov commented on complexes.html
> +      <a class="a-card" href="#">
а тут snake-case

2017-06-14 13:40 UTC, evgenyrodionov commented on complexes.html
> +      <a class="a-card" href="#">
что обозначает a-card?

2017-06-14 13:40 UTC, evgenyrodionov commented on complexes.html
> +            <p class="p-location">SOUTH BEACH, SAN FRANCISCO</p>
p-?

2017-06-14 13:40 UTC, evgenyrodionov commented on complexes.html
> +    <div class="div-footer">
1) используй тег футер
2) зачем префикс div?

2017-06-14 13:40 UTC, evgenyrodionov commented on complexes.html
> +        <div class="footer-ofer row">
ofer это?

2017-06-14 13:40 UTC, evgenyrodionov commented on css/style.css
> +.headline h2 {
на теги не вешаем, говорил же

2017-06-14 13:40 UTC, evgenyrodionov commented on css/style.css
> +a.a-card {
опять же

2017-06-14 13:40 UTC, evgenyrodionov commented on css/style.css
> +div.footer-info p:nth-child(5) {
плохой селектор

2017-06-14 17:22 UTC, alekseevgeorgy commented on complexes.html
> +      <a class="a-card" href="#">
a - ссылка, card - класс
поменял на card-a

2017-06-14 17:26 UTC, alekseevgeorgy commented on complexes.html
> +            <p class="p-location">SOUTH BEACH, SAN FRANCISCO</p>
p is for paragraph
поменял на card-location

2017-06-14 20:23 UTC, alekseevgeorgy commented on complexes.html
> +      <a class="a-card" href="#">
так, card-link вроде более логичнее, поменял на него

2017-06-14 20:57 UTC, alekseevgeorgy commented on complexes.html
> +    <div class="div-footer">
div-footer = необдуманное название wrapper-а
поменял

2017-06-14 20:58 UTC, alekseevgeorgy commented on complexes.html
> +        <div class="footer-ofer row">
ofer = необдуманное название копирайта
поменял на footer-copyright

2017-06-14 20:58 UTC, alekseevgeorgy commented on css/style.css
> +.headline h2 {
поменял это недоразумение во всем документе, теперь везде классы

2017-06-14 20:58 UTC, alekseevgeorgy commented on css/style.css
> +div.footer-info p:nth-child(5) {
понять и простить
убрал и сделал по человечески

2017-06-14 21:12 UTC, imevro requested changes

2017-06-14 21:12 UTC, evgenyrodionov commented on complexes.html
> +    <div class="row hero">
не смешивай свои классы и сетку, говорил же

2017-06-14 21:12 UTC, evgenyrodionov commented on complexes.html
> +      <a class="card-link" href="#">
зачем постфикс линк

2017-06-14 21:12 UTC, evgenyrodionov commented on complexes.html
> +            <div class="card-padding">
плохой нейминг

2017-06-14 21:12 UTC, evgenyrodionov commented on css/style.css
> +.contact-button {
от общего к частному

2017-06-14 21:12 UTC, evgenyrodionov commented on css/style.css
> +  padding: .8125rem 2rem;
давай ещё .7317618368246813612836128 поставим. Откуда этот меджик намберс

2017-06-14 21:35 UTC, alekseevgeorgy commented on complexes.html
> +    <div class="row hero">
везде убрал, тут забыл 🙃 клэссик
исправил

2017-06-14 21:35 UTC, alekseevgeorgy commented on css/style.css
> +  padding: .8125rem 2rem;
обсудили в чате
исправил

2017-06-14 21:35 UTC, alekseevgeorgy commented on css/style.css
> +.contact-button {
точно, спасибо

2017-06-14 21:35 UTC, alekseevgeorgy commented on complexes.html
> +            <div class="card-padding">
пока что самый большой затуп, за который мне стыдно

2017-06-15 09:48 UTC, imevro requested changes

2017-06-15 09:48 UTC, evgenyrodionov commented on complexes.html
>          <div class="card">
у тебя теперь два .card друг в друга вкладываются, зачем?

2017-06-15 10:25 UTC, merged