feat/complexes-page-on-react
alekseevgeorgy/yard-frontend pull request #5
Opened 2017-06-20 13:05 UTC by alekseevgeorgy

пока не разобрался как сделать динамические ссылки для картинок

2017-06-20 13:14 UTC, imevro requested changes

2017-06-20 13:14 UTC, evgenyrodionov commented on public/index.html
> +    <title>React App</title>
неа

2017-06-20 13:14 UTC, evgenyrodionov commented on public/manifest.json
> +  "short_name": "React App",
опять же

2017-06-20 13:14 UTC, evgenyrodionov commented on src/--ComplexesCard.js
> +import React from 'react';
что с названием файла? почему там два деша в начале?

2017-06-20 13:14 UTC, evgenyrodionov commented on src/--ComplexesCard.js
> +import React from 'react';
почему он называется card.js, а тут несколько карточек?

2017-06-20 13:14 UTC, evgenyrodionov commented on src/App.js
> +const Background = styled.div`
в цсс вынеси

2017-06-20 13:14 UTC, evgenyrodionov commented on src/Card.js
> +  box-shadow: 0 0 20px 0px rgba(0, 0, 0, .3);
что с отступами опять

2017-06-20 13:14 UTC, evgenyrodionov commented on src/Card.js
> +const Title = Description.withComponent('h3')
не понял

2017-06-20 13:14 UTC, evgenyrodionov commented on src/Card.js
> +const Title = Description.withComponent('h3')
это как? почему ты считаешь, что тайтл и дескрипшн одинаковые по стилю?

2017-06-20 13:14 UTC, evgenyrodionov commented on src/Card.js
> +const Title = Description.withComponent('h3')
а где ты вообще используешь тайтл?

2017-06-20 13:14 UTC, evgenyrodionov commented on src/Card.js
> +          <Address>{props.address}</Address>
это не адрес, это название ЖК

2017-06-20 13:14 UTC, evgenyrodionov commented on src/Cards.js
> +// const card = {
убери этот мусор

2017-06-20 13:14 UTC, evgenyrodionov commented on src/Cards.js
> +
что за лишний перенос строки

2017-06-20 13:14 UTC, evgenyrodionov commented on src/Cards.js
> +import ComplexesPhoto1 from './img/bitmap1.png';
это не компонент, неправильный стиль нейминга

2017-06-20 13:14 UTC, evgenyrodionov commented on src/Card.js
> +          <Description>The Lewis Steel Building is a masterful industrial conversion located in the heart of Williamsburg. Located at 76 North 4th Street, the former 1930's steel factory has been tra
почему описание не приходит сверху?

2017-06-20 13:14 UTC, evgenyrodionov commented on src/Footer.js
> +const FooterText = styled.p`
ты и так в футере, читай чужие ПРы

2017-06-20 13:32 UTC, alekseevgeorgy commented on src/--ComplexesCard.js
> +import React from 'react';
старые файлы, забыл удалить

2017-06-22 16:39 UTC, alekseevgeorgy commented
Женя, прости, пожалуйста, я знаю, что так делать очень плохо, но ты сам говорил, что нет смысла загружать не законченные вещи. Пока я не прикрутил Роутер, я считал, что это была не законченная часть :( На следующей неделе постараюсь коммитить по чаще и более осмысленно.

2017-06-22 22:03 UTC, imevro requested changes

2017-06-22 22:03 UTC, evgenyrodionov commented on package.json
> +    "normalize": "^0.3.1",
не тот пакет

2017-06-22 22:03 UTC, evgenyrodionov commented on package.json
> +  "name": "compass",
да было норм

2017-06-22 22:03 UTC, evgenyrodionov commented on src/App.css
> +}
имеет смысл вообще это оставлять

2017-06-22 22:03 UTC, evgenyrodionov commented on src/App.js
> +import "./css/fonts.css";
а зачем вообще этот файл

2017-06-22 22:03 UTC, evgenyrodionov commented on src/App.js
> +import ScrollToTopRoute from "./ScrollToTopRoute.js";
опусти .джс

2017-06-22 22:03 UTC, evgenyrodionov commented on src/App.js
> +        <div className="App">
а зачем

2017-06-22 22:03 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +  box-shadow: 0 0 20px 0px rgba(0, 0, 0, .3);
что с отступами

2017-06-22 22:03 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +  font-family: 'Monaco';
а если у меня не стоит монако?

2017-06-22 22:03 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +font-family: 'Fira Sans', serif;
1) отступы
2) фоллбек шрифта без засечек — шрифт с засечками?

2017-06-22 22:03 UTC, evgenyrodionov commented on src/Complexes/List/Headline.jsx
> +    props.marginTopBottom &&
ты тут решил просто поиграться или что?

2017-06-22 22:03 UTC, evgenyrodionov commented on src/Complexes/List/Headline.jsx
> +    props.marginTopBottom &&
не вижу необходимости

2017-06-22 22:03 UTC, evgenyrodionov commented on src/Complexes/List/Headline.jsx
>        <TextTitle>Discover Our New Developments</TextTitle>
а бывает не текст?

2017-06-22 22:03 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +const Description = styled.p`
вынеси это в компонент карточки и там используй вокруг чилдрен

2017-06-22 22:03 UTC, evgenyrodionov commented on src/Complexes/Show/Display.jsx
> +import photo1 from "../../img/complex-page-photos/photo1.png";
не понял, ты же вроде паблик директорию используешь?

2017-06-22 22:03 UTC, evgenyrodionov commented on src/Complexes/Show/Info.jsx
> +font-size: 0.875rem;
да блядь что с отступами

2017-06-22 22:03 UTC, evgenyrodionov commented on src/Complexes/Show/Specs.jsx
> +                Количество квартир:
а ты можешь не делать такие переносы? пиздец файл раздувается

2017-06-23 09:28 UTC, imevro requested changes

2017-06-23 09:28 UTC, evgenyrodionov commented on src/App.js
> +import "normalize.css";
в индекс

2017-06-23 09:28 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +    <Card to="/Complex">
поч с большой буквы-то

2017-06-23 14:40 UTC, merged